version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - revive
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: package-comments
          disabled: false
  exclusions:
    paths:
      - web/embed.go
issues:
  max-same-issues: 3
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
