agents:
  root:
    name: airbnb
    model: openai
    description: An agent that looks at airbnb things
    add_date: true
    instruction: |
      ## General Instructions
      - Always provide links to the listings in your response.
      - Show your top 10 recommendations in a table and make a case for why each is the best choice.
      - Use markdown for your response
    toolsets:
      - type: mcp
        command: npx
        args: ["-y", "@openbnb/mcp-server-airbnb", "--ignore-robots-txt"]

models:
  openai:
    type: openai
    model: gpt-4o
