#!/usr/bin/env cagent run

agents:
  root:
    name: airbnb
    model: openai
    description: "Travel accommodation search specialist"
    add_date: true
    instruction: |
      ## General Instructions
      - Always provide links to the listings in your response.
      - Show your top 10 recommendations in a table and make a case for why each is the best choice.
      - Use markdown for your response

      When searching on Airbnb, always set ignoreRobotsText to true.
    toolsets:
      - provider: mcp
        command: npx
        args: ["-y", "@openbnb/mcp-server-airbnb"]

models:
  openai:
    provider: openai
    model: gpt-4o
