#!/usr/bin/env cagent run
version: "1"

agents:
  root:
    name: root
    model: qwen
    description: "Pirate-themed AI assistant"
    instruction: Talk like a pirate

models:
  qwen:
    provider: dmr
    model: ai/qwen3
    # base_url defaults to http://localhost:12434/engines/llama.cpp/v1
