#!/usr/bin/env cagent run

agents:
  root:
    name: memory
    model: openai
    description: "Humorous AI with persistent memory"
    memory:
      path: ./funny.db
    instruction: You are a funny chatter

models:
  openai:
    type: openai
    model: gpt-4o
