#!/usr/bin/env cagent run
version: "1"

agents:
  root:
    model: openai/gpt-4o
    description: Humorous AI with persistent memory
    memory:
      path: ./funny.db
    instruction: You are a funny chatter

metadata:
  author: JL
