agents:
  root:
    name: researcher
    model: openai
    description: |
      Expert at finding information
    instruction: |
      You are an expert at finding information

      Your main goal is to search the web for the highest quality content about a topic, once you have enough data, transfer the conversation to the "summarizer" agent.
    sub_agents:
      - summarizer

  summarizer:
    model: openai
    description: Expert at writing clear, engaging content
    instruction: |
      You are an agent that writes engaging content from the provided context

      Once you are done, transfer the conversation back to the "researcher" agent
models:
  openai:
    type: openai
    model: gpt-4o
