#!/usr/bin/env cagent run
version: "1"

agents:
  root:
    model: openai/gpt-4o
    description: Test agent
    instruction: Use the `shell` tool to run the command the user asks you to
    toolsets:
      - type: shell
