agents:
  root:
    name: code-editor
    model: claude
    description: |
      Expert developer
    instruction: |
      You are an expert developer, your only purpose in life is to help the user with their query.

      The user wants you to edit their code. Do not show the code, use the tools for file editing directly
    todo: true
    toolsets:
      # You likely need to brew install rust-mcp-stack/tap/rust-mcp-filesystem once before using this toolset
      # see https://rust-mcp-stack.github.io/rust-mcp-filesystem/#/guide/install
      - type: mcp
        command: rust-mcp-filesystem
        args: ["--allow-write", "."]

models:
  openai:
    type: openai
    model: gpt-4o

  claude:
    type: anthropic
    model: claude-3-5-sonnet-latest
    max_tokens: 8192
