#!/usr/bin/env cagent run

agents:
  root:
    name: code-editor
    model: claude
    description: |
      Expert developer
    instruction: |
      You are an expert developer, your only purpose in life is to help the user with their query.

      The user wants you to edit their code. Do not show the code, use the tools for file editing directly
    todo: true
    toolsets:
      - provider: filesystem

models:
  openai:
    provider: openai
    model: gpt-4o

  claude:
    provider: anthropic
    model: claude-3-5-sonnet-latest
    max_tokens: 8192
