# docker compose up --build --remove-orphans
services:
  agent:
    build:
      context: ../..
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY
    volumes:
      - ./agents:/agents
    command: ["web", "-d", "/agents", "session.db"]

  gateway:
    image: docker/mcp-gateway
    command:
      - --transport=streaming
      - --servers=duckduckgo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
