services:
  haproxy:
    image: haproxy:3.2-alpine
    ports:
      - "4000:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      litellm:
        condition: service_healthy
      gateway:
        condition: service_healthy

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    command:
      - "--config=/app/config.yaml"
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  gateway:
    image: docker/mcp-gateway
    command:
      - --central
      - --verbose
      - --transport=streaming
      - --port=9011
    env_file:
      - .env.mcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: wget -O- http://localhost:9011/health
      interval: 1s
      timeout: 2s
      retries: 60
      start_period: 1s

  db:
    image: postgres:16
    restart: always
    container_name: litellm_db
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    name: litellm_postgres_data
