model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-4
    litellm_params:
      model: anthropic/claude-4
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3.7
    litellm_params:
      model: anthropic/claude-3.7
      api_key: os.environ/ANTHROPIC_API_KEY