#!/usr/bin/env cagent run

agents:
  root:
    name: eval-agent
    model: gpt4o
    instruction: You are the most helpful agent of all
    toolsets:
      - type: shell

models:
  gpt4o:
    provider: openai
    model: gpt-4o
