name: Release cagent
run-name: Release cagent ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"
      tag:
        description: "Release Tag"
        required: true
        type: string
      changelog:
        description: ""
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build cross platform binaries
        run: task cross

      - name: Create the release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ./dist/linux_arm64/cagent-linux-arm64
            ./dist/linux_amd64/cagent-linux-amd64
            ./dist/darwin_arm64/cagent-darwin-arm64
            ./dist/darwin_amd64/cagent-darwin-amd64
            ./dist/windows_arm64/cagent-windows-arm64.exe
            ./dist/windows_amd64/cagent-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
